const products = [
  {
    name: "Emerald Chesterfield Sofa",
    image: "/images/sofa1.jpg",
    brand: "FurniHub",
    category: "Sofas",
    description: "Premium velvet Chesterfield sofa.",
    price: 89990,
    countInStock: 12,
    rating: 4.8,
    numReviews: 312,
  },
  {
    name: "Walnut Platform Bed",
    image: "/images/bed1.jpg",
    brand: "FurniHub",
    category: "Beds",
    description: "Luxury walnut wood platform bed.",
    price: 119990,
    countInStock: 10,
    rating: 4.9,
    numReviews: 247,
  },
  {
    name: "Atelier Walnut Desk",
    image: "/images/desk1.jpg",
    brand: "FurniHub",
    category: "Office",
    description: "Modern walnut office desk.",
    price: 64990,
    countInStock: 8,
    rating: 4.6,
    numReviews: 78,
  },
  {
    name: "Royal Dining Table",
    image: "/images/dining1.jpg",
    brand: "FurniHub",
    category: "Dining",
    description: "6-seater luxury dining table.",
    price: 75990,
    countInStock: 6,
    rating: 4.7,
    numReviews: 125,
  },
  {
    name: "Classic Wooden Wardrobe",
    image: "/images/wardrobe1.jpg",
    brand: "FurniHub",
    category: "Wardrobes",
    description: "Spacious wooden wardrobe.",
    price: 54990,
    countInStock: 5,
    rating: 4.5,
    numReviews: 89,
  },
  {
    name: "Modern TV Unit",
    image: "/images/tv1.jpg",
    brand: "FurniHub",
    category: "TV Units",
    description: "Elegant TV entertainment unit.",
    price: 32990,
    countInStock: 15,
    rating: 4.4,
    numReviews: 67,
  }
];